import { moduloActividad, actividadTest } from '../../../../helpers/actividadTest';


const nombre = 'ManicYLosPlanetas';

moduloActividad(nombre, () => {

	actividadTest(nombre, {
		solucion: '<xml xmlns=\"http://www.w3.org/1999/xhtml\"><variables></variables><block type=\"al_empezar_a_ejecutar\" id=\"]?^6Rqsep{F-V{vNU`Ge\" deletable=\"false\" movable=\"false\" editable=\"false\" x=\"15\" y=\"15\"><statement name=\"program\"><shadow type=\"required_statement\" id=\"wXD]FL{50PyVf.zz8E!_\"></shadow><block type=\"procedures_callnoreturn\" id=\"(Yc$_^e{MD@$)z:_!_*N\"><mutation name=\"linea_y_uno\"></mutation><next><block type=\"MoverACasillaArriba\" id=\"Z[?u;tri(Dd8yX/mCC{+\"><next><block type=\"ObservarPlaneta\" id=\"IO?1o}:9JNNQEu[0p^Sa\"><next><block type=\"procedures_callnoreturn\" id=\"-J#q}Lit8P`;MsFt-B#q\"><mutation name=\"linea_y_uno\"></mutation><next><block type=\"MoverACasillaArriba\" id=\"YRH,Ui@_8AG+OQ4n#c(D\"><next><block type=\"ObservarPlaneta\" id=\"!a*!D@2m:H||CxHrmm_8\"><next><block type=\"repetir\" id=\"Z~.O{3kh`,h%MO5vrO#o\"><value name=\"count\"><shadow type=\"required_value\" id=\"tuAT3h1[C;G.$3)5b+up\"></shadow><block type=\"math_number\" id=\"1aG%6nXdd;gGGC-fk~gs\"><field name=\"NUM\">5</field></block></value><statement name=\"block\"><shadow type=\"required_statement\" id=\"a/gQECy(;{dh0wx^%uT)\"></shadow><block type=\"procedures_callnoreturn\" id=\"vqQ^[Xb^73F3H`)tEi2P\"><mutation name=\"mover_y_observar\"></mutation></block></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></statement></block><block type=\"procedures_defnoreturn\" id=\"-s*3kQHU52]pXF2b;ng_\" x=\"254\" y=\"18\"><field name=\"NAME\">linea_y_uno</field><statement name=\"STACK\"><block type=\"repetir\" id=\"IOfGgd[Wa_{8MBOtiYA8\"><value name=\"count\"><shadow type=\"required_value\" id=\":OlYM$uZ.aW(QO4d5aLW\"></shadow><block type=\"math_number\" id=\"fVVj*HTV+icJtTMny$aw\"><field name=\"NUM\">5</field></block></value><statement name=\"block\"><shadow type=\"required_statement\" id=\"?s(pIOL)e(Iae7PJiD,2\"></shadow><block type=\"procedures_callnoreturn\" id=\"PHeHnRaKf:1Gf@/6-5(b\"><mutation name=\"mover_y_observar\"></mutation></block></statement><next><block type=\"MoverACasillaArriba\" id=\"BxL;,(PDzpz_md$A1ikY\"><next><block type=\"VolverABordeIzquierdo\" id=\"9mt@D~C6hobV_T##=`)U\"><next><block type=\"ObservarPlaneta\" id=\"V8%i1E?IkM-)4JoxHd;0\"></block></next></block></next></block></next></block></statement></block><block type=\"procedures_defnoreturn\" id=\"{~{A1l4tqs5J;X,We%UA\" x=\"138\" y=\"273\"><field name=\"NAME\">mover_y_observar</field><statement name=\"STACK\"><block type=\"MoverACasillaDerecha\" id=\"v:/Jb:-_?v;RRN`Q~fd_\"><next><block type=\"ObservarPlaneta\" id=\"=zxI$jhyO-|-7^~|U0P6\"></block></next></block></statement></block></xml>',
	});

});