import { moduloActividad, actividadTest } from '../../../../helpers/actividadTest';


const nombre = '1008';

moduloActividad(nombre, () => {

	actividadTest(nombre, {
		solucion: '<xml xmlns="http://www.w3.org/1999/xhtml">\n  <variables></variables>\n  <block type="al_empezar_a_ejecutar" deletable="false" movable="false" editable="false" x="15" y="15">\n    <statement name="program">\n      <shadow type="required_statement"></shadow>\n      <block type="repetir">\n        <value name="count">\n          <shadow type="required_value"></shadow>\n          <block type="math_number">\n            <field name="NUM">2</field>\n          </block>\n        </value>\n        <statement name="block">\n          <shadow type="required_statement"></shadow>\n          <block type="procedures_callnoreturn">\n            <mutation name="Comer fila de sandías"></mutation>\n            <next>\n              <block type="procedures_callnoreturn">\n                <mutation name="Volver atrás"></mutation>\n                <next>\n                  <block type="MoverACasillaArriba">\n                    <next>\n                      <block type="ObservarPlaneta">\n                        <next>\n                          <block type="MoverACasillaArriba"></block>\n                        </next>\n                      </block>\n                    </next>\n                  </block>\n                </next>\n              </block>\n            </next>\n          </block>\n        </statement>\n        <next>\n          <block type="procedures_callnoreturn">\n            <mutation name="Comer fila de sandías"></mutation>\n          </block>\n        </next>\n      </block>\n    </statement>\n  </block>\n  <block type="procedures_defnoreturn" x="267" y="46">\n    <field name="NAME">Volver atrás</field>\n    <statement name="STACK">\n      <block type="repetir">\n        <value name="count">\n          <shadow type="required_value"></shadow>\n          <block type="math_number">\n            <field name="NUM">5</field>\n          </block>\n        </value>\n        <statement name="block">\n          <shadow type="required_statement"></shadow>\n          <block type="MoverACasillaIzquierda"></block>\n        </statement>\n      </block>\n    </statement>\n  </block>\n  <block type="procedures_defnoreturn" x="331" y="215">\n    <field name="NAME">Comer fila de sandías</field>\n    <statement name="STACK">\n      <block type="repetir">\n        <value name="count">\n          <shadow type="required_value"></shadow>\n          <block type="math_number">\n            <field name="NUM">5</field>\n          </block>\n        </value>\n        <statement name="block">\n          <shadow type="required_statement"></shadow>\n          <block type="ObservarPlaneta">\n            <next>\n              <block type="MoverACasillaDerecha"></block>\n            </next>\n          </block>\n        </statement>\n        <next>\n          <block type="ObservarPlaneta"></block>\n        </next>\n      </block>\n    </statement>\n  </block>\n</xml>',
	});

});