import {moduloActividad, actividadTest} from '../../helpers/actividadTest';

const nombre = "ElMonoCuentaDeNuevo";

moduloActividad(nombre);

actividadTest(nombre, {
	solucion: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="al_empezar_a_ejecutar" id="3" deletable="false" movable="false" editable="false" x="0" y="0"><statement name="program"><block type="repetir" id="4" inline="true"><value name="count"><block type="math_number" id="5"><field name="NUM">4</field></block></value><statement name="block"><block type="procedures_callnoreturn" id="6"><mutation name="Contar frutas de columna"></mutation><next><block type="procedures_callnoreturn" id="7"><mutation name="Volver al inicio"></mutation><next><block type="SiguienteColumna" id="8"></block></next></block></next></block></statement><next><block type="procedures_callnoreturn" id="37"><mutation name="Contar frutas de columna"></mutation></block></next></block></statement></block><block type="procedures_defnoreturn" id="9" x="280" y="35"><mutation></mutation><field name="NAME">Volver al inicio</field><statement name="STACK"><block type="hasta" id="10" inline="true"><value name="condition"><block type="estoyInicio" id="11"></block></value><statement name="block"><block type="MoverACasillaArriba" id="12"></block></statement></block></statement></block><block type="procedures_defnoreturn" id="13" x="11" y="201"><mutation></mutation><field name="NAME">Contar frutas de columna</field><statement name="STACK"><block type="repetir" id="14" inline="true"><value name="count"><block type="LargoColumnaActual" id="15"></block></value><statement name="block"><block type="MoverACasillaAbajo" id="16"><next><block type="procedures_callnoreturn" id="17"><mutation name="Contar banana si hay"></mutation><next><block type="procedures_callnoreturn" id="18"><mutation name="Contar manzana si hay"></mutation></block></next></block></next></block></statement></block></statement></block><block type="procedures_defnoreturn" id="19" x="319" y="281"><mutation></mutation><field name="NAME">Contar manzana si hay</field><statement name="STACK"><block type="si" id="20" inline="true"><value name="condition"><block type="tocandoBanana" id="21"></block></value><statement name="block"><block type="Contarbanana" id="22"></block></statement></block></statement></block><block type="procedures_defnoreturn" id="23" x="47" y="393"><mutation></mutation><field name="NAME">Contar banana si hay</field><statement name="STACK"><block type="si" id="24" inline="true"><value name="condition"><block type="tocandoManzana" id="25"></block></value><statement name="block"><block type="Contarmanzana" id="26"></block></statement></block></statement></block></xml>',
});
