import { moduloActividad, actividadTest } from '../../helpers/actividadTest';

const nombre = "ElPlanetaDeCapyYGuyra";

moduloActividad(nombre, () => {

	actividadTest(nombre, {
		solucion: '<xml xmlns=\"http://www.w3.org/1999/xhtml\"><variables></variables><block type=\"al_empezar_a_ejecutar\" id=\"lgiWgiab3D|gXk5XPG#r\" deletable=\"false\" movable=\"false\" editable=\"false\" x=\"15\" y=\"15\"><statement name=\"program\"><shadow type=\"required_statement\" id=\"oYcd^.r.WbRknPUkZiS~\"></shadow><block type=\"RepetirVacio\" id=\"ycm?m+AO/2M!Oo}xfAFw\"><value name=\"count\"><shadow type=\"required_value\" id=\"9qLZ_,O)ZQqbB[1iW:e)\"></shadow><block type=\"Numero\" id=\"@+JN{Wktk0L3lK:G(Y[+\"><field name=\"NUM\">3</field></block></value><statement name=\"block\"><shadow type=\"required_statement\" id=\"fDaor(?1Py1mV,%6T{uh\"></shadow><block type=\"procedures_callnoreturn\" id=\"L@L_Ls$R~w*8T@bCW83\"><mutation name=\"1\"></mutation></block></statement><next><block type=\"VolverAlBordeIzquierdo\" id=\"u1LzCC_K*QLf7%32X6U5\"><next><block type=\"MoverACasillaArriba\" id=\"`HY]T3}!}b?m!G)V|c5{\"><next><block type=\"procedures_callnoreturn\" id=\"Zq!}Y$.#fTT8Y1S`.1G_\"><mutation name=\"1\"></mutation><next><block type=\"VolverAlBordeIzquierdo\" id=\"FhT6t|H{J+g{}Qv_0h8U\"><next><block type=\"MoverACasillaArriba\" id=\"00]A5pj|+Qull`ei*w=.\"><next><block type=\"RepetirVacio\" id=\"U9dl.^.8S#r;/!Qw4v*y\"><value name=\"count\"><shadow type=\"required_value\" id=\"4YpQlNky|ixGY.SQf4:g\"></shadow><block type=\"Numero\" id=\"YMQoWW.-h(n}@OcueIvy\"><field name=\"NUM\">4</field></block></value><statement name=\"block\"><shadow type=\"required_statement\" id=\"udT6OF`BpWiUE_@|vws5\"></shadow><block type=\"procedures_callnoreturn\" id=\"+t#[psTS42k6VY}wCZGO\"><mutation name=\"1\"></mutation></block></statement><next><block type=\"VolverAlBordeIzquierdo\" id=\"_OcGH,P^bbSbM}u]a~(3\"><next><block type=\"MoverACasillaArriba\" id=\"9eYecPw,Ke,3`S43I*PG\"><next><block type=\"RepetirVacio\" id=\"6@g5n-E^*8-g.QpClz@y\"><value name=\"count\"><shadow type=\"required_value\" id=\"n#k$IiNIOs=I.^aXBHX@\"></shadow><block type=\"Numero\" id=\"`%/a7(kS~IN(p5IY+qh8\"><field name=\"NUM\">2</field></block></value><statement name=\"block\"><shadow type=\"required_statement\" id=\"/%^DBCRnC~ypKtutK0-*\"></shadow><block type=\"procedures_callnoreturn\" id=\"fpo7EAQUTVV$=K;,!1X*\"><mutation name=\"1\"></mutation></block></statement></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></next></block></statement></block><block type=\"procedures_defnoreturn\" id=\"r0A%I?WQbp5]yZ(mZ;k@\" x=\"328\" y=\"60\"><field name=\"NAME\">1</field><statement name=\"STACK\"><block type=\"MoverACasillaDerecha\" id=\"][v=f05Ok/X{aI7NBW.F\"><next><block type=\"RecogerLata\" id=\"cB|jZbdLu5s,3L+,IE*5\"></block></next></block></statement></block></xml>',
	});

});