import {moduloActividad, actividadTest} from '../../helpers/actividadTest';

let nombre = "TitoCuadrado";

moduloActividad(nombre);

actividadTest(nombre, {
	solucion: '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="al_empezar_a_ejecutar" id="13" deletable="false" movable="false" editable="false" x="0" y="0"><statement name="program"><block type="procedures_callnoreturn" id="14" inline="true"><mutation name="Prender luces hacia"><arg name="direccion"></arg></mutation><value name="ARG0"><block type="ParaLaDerecha" id="15"></block></value><next><block type="procedures_callnoreturn" id="20" inline="true"><mutation name="Prender luces hacia"><arg name="direccion"></arg></mutation><value name="ARG0"><block type="ParaAbajo" id="21"></block></value><next><block type="procedures_callnoreturn" id="16" inline="true"><mutation name="Prender luces hacia"><arg name="direccion"></arg></mutation><value name="ARG0"><block type="ParaLaIzquierda" id="17"></block></value><next><block type="procedures_callnoreturn" id="18" inline="true"><mutation name="Prender luces hacia"><arg name="direccion"></arg></mutation><value name="ARG0"><block type="ParaArriba" id="19"></block></value></block></next></block></next></block></next></block></statement></block><block type="procedures_defnoreturn" id="22" x="0" y="196"><mutation><arg name="direccion"></arg></mutation><field name="NAME">Prender luces hacia</field><statement name="STACK"><block type="repetir" id="23" inline="true"><value name="count"><block type="math_number" id="24"><field name="NUM">6</field></block></value><statement name="block"><block type="MoverA" id="25" inline="true"><value name="direccion"><block type="param_get" id="26"><field name="VAR">direccion</field></block></value><next><block type="procedures_callnoreturn" id="27"><mutation name="Prender luz si hay"></mutation></block></next></block></statement></block></statement></block><block type="procedures_defnoreturn" id="28" x="2" y="363"><mutation></mutation><field name="NAME">Prender luz si hay</field><statement name="STACK"><block type="si" id="29" inline="true"><value name="condition"><block type="tocandoLuz" id="30"></block></value><statement name="block"><block type="EncenderLuz" id="31"></block></statement></block></statement></block></xml>',
});
